name: Update Requirements

on:
  push:
    paths:
      - 'requirements.txt'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Create requirements directory
      run: mkdir -p requirements

    - name: Download dependencies
      run: pip download -r requirements.txt -d requirements

    - name: Package requirements
      run: tar -czvf requirements.tar.gz requirements

    - name: Upload requirements package
      uses: actions/upload-artifact@v4
      with:
        name: requirements-package
        path: requirements.tar.gz

    
